# ASP.NET Core (.NET Framework)

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: ShellScript@2
  inputs:
    scriptPath: ./build.sh

- task: ShellScript@2
  inputs:
    scriptPath: ./tests.sh