# ASP.NET Core (.NET Framework)

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- deployment: start
  continueOnError: false
  environment: 'dev1'
  timeoutInMinutes: 120
  strategy:
    runOnce:
      deploy:
        steps:
          - task: ShellScript@2
            inputs:
              scriptPath: ./build.sh

          - task: ShellScript@2
            inputs:
              scriptPath: ./tests.sh
